# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-28 15:50
from __future__ import unicode_literals

import courseware.fields
from django.db import migrations
from django.db.migrations import AlterField

class CsmBigInt(AlterField):
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        if schema_editor.connection.alias == 'student_module_history':
            schema_editor.execute("ALTER TABLE `courseware_studentmodule` MODIFY `id` bigint UNSIGNED AUTO_INCREMENT NOT NULL;")
        else:
            schema_editor.execute("ALTER TABLE `courseware_studentmodulehistory` MODIFY `student_module_id` bigint UNSIGNED NOT NULL;")

class Migration(migrations.Migration):

    dependencies = [
        ('courseware', '0010_auto_20190709_1559'),
    ]

    operations = [
        CsmBigInt(
            model_name='studentmodule',
            name='id',
            field=courseware.fields.UnsignedBigIntAutoField(primary_key=True, serialize=False),
        )
    ]
