# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-28 15:50
from __future__ import unicode_literals

import courseware.fields
from django.db import migrations

def forwards(apps, schema_editor):
    # Only run if we're connected to the student_module_history db
    if schema_editor.connection.alias != 'student_module_history':
        return

    migrations.AlterField(
        model_name='studentmodule',
        name='id',
        field=courseware.fields.UnsignedBigIntAutoField(primary_key=True, serialize=False),
    )

class Migration(migrations.Migration):

    dependencies = [
        ('courseware', '0010_auto_20190709_1559'),
    ]

    operations = [
        migrations.RunPython(forwards, reverse_code=migrations.RunPython.noop),
    ]
